name: taiga_sounds
description: Taiga Sounds soundboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  http: ^1.5.0
  path_provider: ^2.1.5
  file_picker: ^10.3.8
  # Additional dependencies to support recording and trimming audio.
  flutter_sound: ^9.2.13+1
  # FFmpeg kit is required for combining audio files when creating a new
  # sound. Use the audio‑only variant to keep the app size down. See
  # https://pub.dev/packages/ffmpeg_kit_audio_flutter for details.
  ffmpeg_kit_audio_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
